### ISSUE TITLE
[Nathanmac\Utilities\Parser\Exceptions\ParserException] Failed To Parse XML    

### ISSUE THREAD

**Issue by KudlaiViktor** [nathanmac/Parser#12]
I'm trying to parse shoutcast streams file in XSPF format.
Everything works fine but sometimes getting an error:

**[Nathanmac\Utilities\Parser\Exceptions\ParserException]**
**Failed To Parse XML**

My XSPF file:
```
<?xml version="1.0" encoding="utf-8"?>
	<playlist version="1" xmlns="http://xspf.org/ns/0/">
	<title>HARDCORERADIO.NL - Hardcore radio - 24/7 Mainstream Hardcore & Gabber</title>
	<trackList>
		<track>
			<location>http://81.18.165.235:80</location>
			<title>HARDCORERADIO.NL - Hardcore radio - 24/7 Mainstream Hardcore & Gabber</title>
		</track>
		<track>
			<location>http://81.18.165.236:80</location>
			<title>HARDCORERADIO.NL - Hardcore radio - 24/7 Mainstream Hardcore & Gabber</title>
		</track>
		<track>
			<location>http://81.18.165.234:80</location>
			<title>HARDCORERADIO.NL - Hardcore radio - 24/7 Mainstream Hardcore & Gabber</title>
		</track>
	</trackList>
	</playlist>
```

Stack trace:
```
[2015-07-10 08:20:17] production.ERROR: exception 'Nathanmac\Utilities\Parser\Exceptions\ParserException' with message 'Failed To Parse XML' in /vagrant/shared/muzza/vendor/nathanmac/parser/src/Formats/XML.php:31
Stack trace:
#0 /vagrant/shared/muzza/vendor/nathanmac/parser/src/Parser.php(193): Nathanmac\Utilities\Parser\Formats\XML->parse('<?xml version="...')
#1 /vagrant/shared/muzza/vendor/nathanmac/parser/src/Parser.php(209): Nathanmac\Utilities\Parser\Parser->parse('<?xml version="...', Object(Nathanmac\Utilities\Parser\Formats\XML))
#2 /vagrant/shared/muzza/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Nathanmac\Utilities\Parser\Parser->xml('<?xml version="...')
#3 /vagrant/shared/muzza/app/parsers/ShoutCastParser.php(62): Illuminate\Support\Facades\Facade::__callStatic('xml', Array)
#4 /vagrant/shared/muzza/app/parsers/ShoutCastParser.php(62): Nathanmac\Utilities\Parser\Facades\Parser::xml('<?xml version="...')
#5 /vagrant/shared/muzza/app/commands/Streams.php(52): App\Parsers\ShoutCastParser::parseStreamsByStationId()
#6 /vagrant/shared/muzza/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Streams->fire()
#7 /vagrant/shared/muzza/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /vagrant/shared/muzza/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /vagrant/shared/muzza/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /vagrant/shared/muzza/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Streams), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /vagrant/shared/muzza/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /vagrant/shared/muzza/artisan(59): Symfony\Component\Console\Application->run()
#13 {main} [] []

```

**Comment by KudlaiViktor** [comment]
I found difference between successful XML files and failed.
Successful files end with some IP address (ex. http://67.212.189.20:80)

Successful XML file: 
```
<?xml version="1.0" encoding="utf-8"?>
	<playlist version="1" xmlns="http://xspf.org/ns/0/">
		<title>Devil's Night Radio!</title>
		<trackList>
			<track>
				<location>http://67.212.189.20:80</location>
				<title>Devil's Night Radio!</title>
			</track>
		</trackList>
	</playlist>http://67.212.189.20:80
```
Any advice? Thanks.
